// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import Header from "./components/Header";
import Footer from "./components/Footer";
import MouseEffect from "../app/components/MouseEffect"


export const metadata = {
  title: "Sobha Dubai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <MouseEffect/>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
